/* elfuse VM launch: bring-up + GDB + run loop + teardown
 *
 * Copyright 2026 elfuse contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Implementation of elfuse_launch (contract and caller/callee ownership in
 * launch.h). It lives apart from src/main.c so bring-up is one path behind a
 * struct, leaving CLI concerns (option parsing, sysroot provisioning, the
 * shebang loop) in main().
 *
 * shim_blob.h is included here, not in src/main.c, so the static
 * shim_bin / shim_bin_len blob has a single object definition site.
 */

#include "launch.h"

#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "core/bootstrap.h"
#include "core/guest.h"
#include "core/shim-globals.h"
#include "core/sysroot.h"

#include "runtime/futex.h"   /* futex_interrupt_request */
#include "runtime/procemu.h" /* proc_pty_release_process_slaves */
#include "runtime/thread.h"
#include "syscall/path.h"
#include "syscall/proc.h"
#include "syscall/wakeup-pipe.h"

#include "debug/gdbstub.h"
#include "debug/log.h"
#include "debug/syscall-hist.h"

/* Embedded shim binary (generated by xxd -i from shim.bin). */
#include "shim_blob.h"

/* The shim code slot in the infra reserve is sized tight (INFRA_SHIM_SLOT, a
 * few x the current blob) so the rest of the reserve goes to the page-table
 * pool. If the shim ever outgrows the slot it would overlap the shim-data
 * block; fail the build loudly rather than corrupt memory at boot. Enlarge
 * INFRA_SHIM_SLOT (and shrink the pool to match) if this fires.
 */
_Static_assert(sizeof(shim_bin) <= INFRA_SHIM_SLOT,
               "shim blob exceeds its infra slot; bump INFRA_SHIM_SLOT");

int elfuse_launch(const launch_args_t *args)
{
    extern char **environ;
    char **envp_use = args->envp ? args->envp : environ;

    guest_t g;
    bool guest_initialized = false;
    guest_bootstrap_t boot;
    /* Local copy of the temp flag (ownership contract in launch.h): the
     * caller's launch_args_t is const, and the flag must drop once the
     * unlink happens.
     */
    bool elf_host_temp = args->elf_host_temp;
    /* The guest-visible entrypoint path is argv[0]; elf_path is the
     * resolved host path to that binary. They differ when path
     * translation or a FUSE-materialized temp is involved.
     */
    const char *elf_guest_path = (args->guest_argc > 0 && args->guest_argv)
                                     ? args->guest_argv[0]
                                     : args->elf_path;

    /* Fakeroot means the guest starts as uid/gid 0: proc_identity_init's
     * defaults and the ELFUSE_FAKEROOT_EXEC transition both set root together
     * with the flag, and uid_is_permitted() grants every setuid under fakeroot
     * on that basis. A non-root identity request would keep that grant while
     * reporting an unprivileged uid, so the guest could call setuid(0) at
     * will. Enforced here, as with the Rosetta GDB check below.
     */
    if (proc_fakeroot_enabled() && args->has_creds &&
        (args->uid != 0 || args->gid != 0)) {
        log_error(
            "--fakeroot runs the guest as uid/gid 0 and cannot be combined "
            "with --user %u:%u",
            args->uid, args->gid);
        goto fail;
    }

    /* Stage --user before bring-up; proc.h states why it cannot be applied
     * afterwards.
     */
    if (args->has_creds)
        proc_set_initial_ids(args->uid, args->gid);

    if (guest_bootstrap_prepare(
            &g, args->elf_path, elf_host_temp, elf_guest_path, args->sysroot,
            args->guest_argc, args->guest_argv, envp_use, shim_bin,
            shim_bin_len, args->verbose, &guest_initialized, &boot) < 0)
        goto fail;

    /* A FUSE-materialized temp has been loaded; drop it once the guest
     * has its own mapping, unless Rosetta still needs the reopenable
     * host path.
     */
    if (elf_host_temp && !g.is_rosetta) {
        unlink(args->elf_path);
        elf_host_temp = false;
    }

    /* Reject GDB for a Rosetta (x86_64) guest here, not just in main(): the
     * stub exposes the aarch64 shim's register/memory view, which is the wrong
     * architecture for a Rosetta-translated x86_64 guest. main() rejects it up
     * front via a static ELF probe, but enforcing it in elfuse_launch (once
     * bring-up has set g.is_rosetta) makes every caller inherit the constraint,
     * including the planned OCI run helper.
     */
    if (args->gdb_port > 0 && g.is_rosetta) {
        log_error(LAUNCH_GDB_X86_64_MSG);
        goto fail;
    }

    if (args->sysroot) {
        bool case_sensitive = true;
        bool case_preserving = true;
        if (sysroot_probe_case_sensitivity(args->sysroot, &case_sensitive,
                                           &case_preserving) == 0)
            proc_set_sysroot_casefold(case_preserving && !case_sensitive);
        else
            proc_set_sysroot_casefold(false);
    } else {
        proc_set_sysroot_casefold(false);
    }

    /* The guest cwd is the host process cwd, as in sys_chdir's real-directory
     * branch; placed after the casefold probe so path_translate_at sees the
     * sysroot's real case behavior.
     */
    if (args->cwd_guest && args->cwd_guest[0] != '\0') {
        path_translation_t tx;
        if (path_translate_at(LINUX_AT_FDCWD, args->cwd_guest, PATH_TR_NONE,
                              &tx) < 0) {
            log_error("failed to resolve working directory %s: %s",
                      args->cwd_guest, strerror(errno));
            goto fail;
        }
        /* A shm leaf needs sys_chdir's O_NOFOLLOW fd and virtual-cwd publish;
         * entering it here would add a holder of the never-follow invariant
         * dev_shm_resolve_path() enumerates. Refuse instead.
         */
        if (tx.is_dev_shm) {
            log_error("--workdir %s: /dev/shm is not supported",
                      args->cwd_guest);
            goto fail;
        }
        /* proc_resolve_sysroot_path() hands back the host spelling for a path
         * the sysroot does not hold, the overlay contract for guest syscalls,
         * but that would start the guest in a same-named host directory
         * outside the tree --workdir named. Demand containment against the
         * canonical prefix from proc_sysroot_snapshot() instead.
         */
        if (args->sysroot) {
            char sr[LINUX_PATH_MAX];
            if (!proc_sysroot_snapshot(sr, sizeof(sr))) {
                log_error("failed to read the sysroot prefix for --workdir %s",
                          args->cwd_guest);
                goto fail;
            }
            /* Same carve-out as path_dirent_dir_holds_escapes(): "--sysroot /"
             * owns every host path, but path_prefix_match on a bare separator
             * accepts "/" alone.
             */
            size_t srlen = strlen(sr);
            if (srlen > 1 && !path_prefix_match(tx.host_path, sr, srlen)) {
                log_error("--workdir %s does not resolve inside the sysroot",
                          args->cwd_guest);
                goto fail;
            }
        }
        if (chdir(tx.host_path) < 0) {
            log_error("failed to set working directory %s: %s", args->cwd_guest,
                      strerror(errno));
            goto fail;
        }
        if (proc_cwd_refresh() < 0)
            proc_cwd_invalidate();
    }

    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    if (guest_bootstrap_create_vcpu(&g, &boot, args->verbose, &vcpu, &vexit) <
        0)
        goto fail;

    /* GDB setup must happen before the first run so entry-stop and
     * hardware breakpoints can affect the initial vCPU.
     */
    if (args->gdb_port > 0) {
        if (gdb_stub_init(args->gdb_port, &g) < 0) {
            log_error("failed to initialize GDB stub");
            goto fail;
        }
        gdb_stub_sync_debug_regs(vcpu);
        if (args->gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    }

    /* vcpu_run_loop owns guest execution until exit, fatal signal, or timeout.
     */
    int exit_code =
        vcpu_run_loop(vcpu, vexit, &g, args->verbose, args->timeout_sec, NULL);

    /* Tear down debugger state before joining workers: a worker parked in
     * gdb_stub_handle_stop() stays active (not deactivated) until this
     * broadcasts resume_cond, so joining first would just time out and
     * detach it while it is still paused.
     */
    gdb_stub_shutdown();

    /* Join worker vCPU threads before guest_destroy unmaps the guest slab: a
     * sibling still mid-iteration in its own run loop would fault on freed
     * guest memory and crash the host with SIGSEGV, masking the real exit
     * code. The join is a no-op once workers have wound down (the common
     * single-threaded case).
     *
     * vcpu_run_loop can also return via a bare break (alarm timeout 124, a
     * fatal default-disposition signal, or ELR_EL1==0) with no one having
     * requested exit_group or kicked the siblings out of hv_vcpu_run. Mirror
     * guest_destroy's request-interrupt prefix here first; otherwise this join
     * burns its full poll cap and detaches every worker, and guest_destroy's
     * own interrupt-join skips them (it honors join_abandoned), leaving live
     * pthreads to fault on the imminent unmap.
     */
    if (!proc_exit_group_requested())
        proc_request_exit_group(0);
    futex_interrupt_request();
    wakeup_pipe_signal();
    thread_interrupt_all();
    /* Workers parked on internal condvars (fork barrier, ptrace stop/wait)
     * see neither the pipe nor the vCPU kick; broadcast so they re-check the
     * exit-group flag and terminate before the join below gives up on them.
     */
    thread_wake_exit_waiters();
    thread_join_workers();

    /* Diagnostic counter dump runs before guest_destroy so the
     * shim_data mapping is still valid. ELFUSE_SHIM_STATS is the gate;
     * an unset variable produces no output.
     */
    if (shim_globals_stats_enabled())
        shim_globals_counters_dump(&g);

    /* Dump the startup histogram before guest_destroy so any
     * cleanup-path syscalls (closing host fds, unmapping the slab) do
     * not appear in the captured set. The dump is a no-op when
     * ELFUSE_STARTUP_TRACE=syscalls was not requested.
     */
    syscall_hist_dump();

    /* Give back any pty slaves this process still holds before the guest
     * teardown below. The guest's stdio slaves are closed by the kernel,
     * not by the guest, so they never pass through the per-fd close hook; a
     * master in another process would otherwise wait forever for a hangup
     * this exit should have produced. Bring-up failures skip this: the fail
     * path is only reachable before the run loop, so no slave exists yet.
     */
    proc_pty_release_process_slaves();

    if (guest_initialized)
        guest_destroy(&g);

    /* Rosetta guests keep the FUSE-materialized temp alive for the whole run
     * (the translator reopens the host path); drop it now that the guest is
     * gone so repeated Rosetta launches do not accumulate temp files.
     */
    if (elf_host_temp)
        unlink(args->elf_path);

    return exit_code;

fail:
    /* Bring-up failed: unwind whatever exists so far, including the temp
     * unlink this side owns past the prepare call (contract in launch.h).
     * Staged --user credentials are dropped too (proc.h).
     */
    proc_clear_initial_ids();
    if (guest_initialized)
        guest_destroy(&g);
    if (elf_host_temp)
        unlink(args->elf_path);
    return 1;
}
