/* elfuse VM launch: bring-up + GDB + run loop + teardown
 *
 * Copyright 2026 elfuse contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Extracted from src/main.c so the oci run orchestrator and the legacy
 * positional-ELF main can share one bring-up path. The function
 * deliberately does NOT touch the original CLI argv block: proctitle
 * rewriting must happen in the caller, before elfuse_launch, because the
 * caller owns the only pointer to the original argv (the heap-copied
 * guest_argv hands a different string region to the guest).
 *
 * The function does not save/restore host cwd. Callers that care about
 * post-exit host cwd preservation snapshot it themselves; this matches
 * the pre-refactor main() shape where the cwd save lived alongside the
 * CLI parsing rather than the bring-up. Same goes for sysroot_mount
 * cleanup -- the --create-sysroot detach belongs to whoever provisioned
 * the mount, not to the launch.
 *
 * shim_blob.h carries the embedded EL1 kernel shim. It is included here
 * rather than in src/main.c so symbol shim_bin / shim_bin_len has a
 * single definition site once the legacy main was reshaped to call
 * elfuse_launch. Any other future caller that needs the shim bytes
 * directly should pull them from here.
 */

#include "launch.h"

#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <stdbool.h>
#include <stdlib.h>

#include "core/bootstrap.h"
#include "core/guest.h"
#include "core/sysroot.h"

#include "syscall/proc.h"

#include "debug/gdbstub.h"
#include "debug/log.h"

/* Embedded shim binary (generated by xxd -i from shim.bin). */
#include "shim_blob.h"

int elfuse_launch(const launch_args_t *args)
{
    if (!args) {
        log_error("elfuse_launch: NULL args");
        return 1;
    }

    extern char **environ;
    char **envp_use = args->envp ? (char **) (uintptr_t) args->envp : environ;

    guest_t g;
    bool guest_initialized = false;
    guest_bootstrap_t boot;
    /* oci_run pre-resolves the entrypoint: args->elf_path is the host path
     * under the cloned rootfs and guest_argv[0] is the guest-absolute path
     * the guest should see (/proc/self/exe, argv[0]). The binary is a real
     * file in the rootfs, never a FUSE-materialized temp, so the host-path
     * temp flag is false. (guest_bootstrap_prepare's split of host vs guest
     * path landed with the rosetta work; the caller resolves the host path.)
     */
    const char *elf_guest_path = (args->guest_argc > 0 && args->guest_argv)
                                     ? args->guest_argv[0]
                                     : args->elf_path;
    if (guest_bootstrap_prepare(
            &g, args->elf_path, false, elf_guest_path, args->sysroot,
            args->guest_argc, args->guest_argv, envp_use, shim_bin,
            shim_bin_len, args->verbose, &guest_initialized, &boot) < 0) {
        if (guest_initialized)
            guest_destroy(&g);
        return 1;
    }

    if (args->sysroot) {
        bool case_sensitive = true;
        bool case_preserving = true;
        if (sysroot_probe_case_sensitivity(args->sysroot, &case_sensitive,
                                           &case_preserving) == 0)
            proc_set_sysroot_casefold(case_preserving && !case_sensitive);
        else
            proc_set_sysroot_casefold(false);
    } else {
        proc_set_sysroot_casefold(false);
    }

    if (args->has_creds)
        proc_set_ids(args->uid, args->uid, args->uid, args->gid, args->gid,
                     args->gid);

    /* cwd_guest carries the image WorkingDir once oci_run materializes it
     * under the cloned rootfs; the legacy positional-ELF main passes NULL
     * and the guest inherits the host cwd instead.
     */
    (void) args->cwd_guest;

    /* fork_child / vfork_notify dispatch stays in main() for now (early
     * return before reaching elfuse_launch). The fields are kept on
     * launch_args_t so callers route through one launch struct shape
     * even when the IPC plumbing changes.
     */
    (void) args->fork_child_fd;
    (void) args->vfork_notify_fd;

    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    if (guest_bootstrap_create_vcpu(&g, &boot, args->verbose, &vcpu, &vexit) <
        0) {
        if (guest_initialized)
            guest_destroy(&g);
        return 1;
    }

    /* GDB setup must happen before the first run so entry-stop and
     * hardware breakpoints can affect the initial vCPU.
     */
    if (args->gdb_port > 0) {
        if (gdb_stub_init(args->gdb_port, &g) < 0) {
            log_error("failed to initialize GDB stub");
            if (guest_initialized)
                guest_destroy(&g);
            return 1;
        }
        /* Mirror any preconfigured breakpoints/watchpoints into this
         * vCPU.
         */
        gdb_stub_sync_debug_regs(vcpu);
        if (args->gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    }

    /* vcpu_run_loop owns guest execution until exit, fatal signal, or
     * timeout.
     */
    int exit_code =
        vcpu_run_loop(vcpu, vexit, &g, args->verbose, args->timeout_sec);

    /* Tear down debugger state before freeing guest/vCPU resources. */
    gdb_stub_shutdown();
    if (guest_initialized)
        guest_destroy(&g);

    return exit_code;
}
