/*
 * Run aarch64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2026 elfuse contributors
 * Copyright 2025 Moritz Angermann, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MiB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *
 * Usage: elfuse [options] <elf-path> [args...]; `elfuse --help` lists the
 * options. The flag list lives once in ELFUSE_USAGE_BODY below; --help and
 * the argument-error paths render it differently but cannot drift apart.
 */

#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/resource.h>
#include <unistd.h>

#include "utils.h"
#include "elfuse-limits.h"

#include "core/bootstrap.h"
#include "core/guest.h"
#include "core/launch.h"
#include "core/rosetta.h"
#include "core/sysroot.h"

#include "runtime/forkipc.h"
#include "runtime/proctitle.h"

#include "syscall/fuse.h"
#include "syscall/path.h"
#include "syscall/proc.h"
#include "syscall/wakeup-pipe.h"

#include "debug/log.h"
#include "debug/syscall-hist.h"

static int parse_int_arg(const char *s, int min, int max, int *out)
{
    /* Seed end with s (strtol's no-conversion result) so the end == s guard
     * below catches a failed parse without a separate NULL check.
     */
    char *end = (char *) s;
    errno = 0;
    long value = strtol(s, &end, 10);
    if (errno != 0 || end == s || *end != '\0' || value < min || value > max)
        return -1;
    *out = (int) value;
    return 0;
}

static int resolve_guest_elf_host_path(const char *elf_guest_path,
                                       char *elf_host_path,
                                       size_t elf_host_path_sz,
                                       bool *elf_host_temp)
{
    path_translation_t tx;
    if (!elf_guest_path || !elf_host_path || elf_host_path_sz == 0 ||
        !elf_host_temp) {
        errno = EINVAL;
        return -1;
    }

    *elf_host_temp = false;
    if (path_translate_at(LINUX_AT_FDCWD, elf_guest_path, PATH_TR_NONE, &tx) <
        0)
        return -1;

    if (tx.fuse_path) {
        int rc = fuse_materialize_path(tx.intercept_path, elf_host_path,
                                       elf_host_path_sz);
        if (rc < 0) {
            errno = -rc;
            return -1;
        }
        *elf_host_temp = true;
        return 0;
    }

    size_t len = str_copy_trunc(elf_host_path, tx.host_path, elf_host_path_sz);
    if (len >= elf_host_path_sz) {
        errno = ENAMETOOLONG;
        return -1;
    }
    return 0;
}

static void free_guest_argv(const char **guest_argv, int guest_argc)
{
    if (!guest_argv)
        return;
    for (int i = 0; i < guest_argc; i++)
        free((void *) guest_argv[i]);
    free((void *) guest_argv);
}

/* The infra-reserve layout invariants documented in guest.h are derived from
 * raw offset constants, so a future edit that grows the pool by shifting one
 * offset without the others would silently overlap two regions. Enforce them at
 * build time rather than trusting the comment.
 */
_Static_assert(INFRA_PT_POOL_END_OFF == INFRA_SHIM_OFF,
               "PT pool must end exactly where the shim slot begins");
_Static_assert(INFRA_SHIM_DATA_OFF + BLOCK_2MIB == INFRA_RESERVE,
               "shim_data must occupy the top 2MiB block of the reserve");
_Static_assert((INFRA_SHIM_DATA_OFF & (BLOCK_2MIB - 1)) == 0,
               "shim_data must be 2MiB-aligned");
_Static_assert((INFRA_PT_POOL_OFF & 0xFFF) == 0 &&
                   (INFRA_PT_POOL_END_OFF & 0xFFF) == 0,
               "PT pool offsets must be page-aligned");

/* Build-time version string (generated by make into build/version.h) */
#include "version.h"

static int host_nofile_ensure_capacity(void)
{
    const rlim_t required = (rlim_t) HOST_NOFILE_MIN;
    struct rlimit limit;

    if (getrlimit(RLIMIT_NOFILE, &limit) < 0) {
        log_error("failed to read host RLIMIT_NOFILE: %s", strerror(errno));
        return -1;
    }
    if (limit.rlim_cur >= required)
        return 0;

    if (limit.rlim_max != RLIM_INFINITY && limit.rlim_max < required) {
        log_error(
            "host RLIMIT_NOFILE hard limit %llu is below the required %llu "
            "(%d guest FDs + %d elfuse reserve)",
            (unsigned long long) limit.rlim_max, (unsigned long long) required,
            FD_TABLE_SIZE, HOST_FD_RESERVE);
        return -1;
    }

    rlim_t old_soft = limit.rlim_cur;
    limit.rlim_cur = required;
    if (setrlimit(RLIMIT_NOFILE, &limit) < 0) {
        log_error("failed to raise host RLIMIT_NOFILE from %llu to %llu: %s",
                  (unsigned long long) old_soft, (unsigned long long) required,
                  strerror(errno));
        return -1;
    }

    return 0;
}

/* Verify the host CPU's DC ZVA granule matches the shim's hardcoded value.
 *
 * DCZID_EL0 is readable from EL0 without trapping, so guest libc reads the
 * host's value directly and uses it as the stride for memset(0) loops. The shim
 * emulates each trapped DC ZVA by zeroing exactly 64 bytes (src/core/shim.S).
 * Apple Silicon M1..M4 report DCZID_EL0.BS=4 (64 bytes); any future host that
 * advertises a different granule would cause silent partial-zero corruption of
 * guest memory. Abort here so the mismatch surfaces at startup instead of as
 * data corruption later.
 */
static int host_dc_zva_assert(void)
{
    uint64_t dczid;
    __asm__ volatile("mrs %0, DCZID_EL0" : "=r"(dczid));
    if (dczid & (1ULL << 4)) {
        log_error(
            "host CPU prohibits DC ZVA (DCZID_EL0.DZP=1); cannot run "
            "guests that depend on it");
        return -1;
    }
    unsigned bs = (unsigned) (dczid & 0xF);
    if (bs != 4) {
        log_error(
            "host DCZID_EL0.BS=%u (%u-byte DC ZVA block) but the shim "
            "emulates 64 bytes; update src/core/shim.S before running",
            bs, 1u << (bs + 2));
        return -1;
    }
    return 0;
}

/* Usage synopsis: one flag list, two renderings. @sep joins the groups,
 * with a space for ELFUSE_USAGE and a newline plus an indent to the column
 * after "usage: elfuse " for ELFUSE_USAGE_WRAPPED.
 *
 * The error paths need the flat form because log_error stamps a timestamp
 * and a source location on the first line only, so a wrapped string prints
 * ragged under the prefix; --help has no prefix and takes the wrapped form,
 * which fits 80 columns. Sharing one body keeps the flag list from drifting
 * between them (one copy had already lost the --gdb flags).
 */
#define ELFUSE_USAGE_BODY(sep)                                     \
    "usage: elfuse [--verbose] [--timeout N] [--sysroot PATH]" sep \
    "[--create-sysroot PATH] [--no-rosetta] [--fakeroot]" sep      \
    "[--gdb PORT] [--gdb-stop-on-entry]" sep                       \
    "[--user UID[:GID]] [--workdir DIR] <elf-path> [args...]"

#define ELFUSE_USAGE ELFUSE_USAGE_BODY(" ")
#define ELFUSE_USAGE_WRAPPED ELFUSE_USAGE_BODY("\n              ")

int main(int argc, char **argv)
{
    log_init();

    /* Resolve ELFUSE_STARTUP_TRACE before any guest syscall can fire so the
     * histogram captures the very first dynamic-linker openat.
     */
    syscall_hist_init();

    bool verbose = false;

    /* x86_64-via-Rosetta is on by default; --no-rosetta or ELFUSE_NO_ROSETTA=1
     * disables it. Architecture is auto-detected from the ELF header in
     * guest_bootstrap_prepare; the access() probe in rosetta_prepare surfaces
     * an install hint if Rosetta is not present.
     */
    bool rosetta_enabled = true;
    int timeout_sec = 10, fork_child_fd = -1, vfork_notify_fd = -1;
    const char *sysroot = NULL;
    const char *create_sysroot = NULL;
    int gdb_port = 0;
    bool gdb_stop_on_entry = false;
    bool fakeroot = false;
    bool has_creds = false;
    uint32_t uid = 0, gid = 0;
    char *workdir = NULL;
    int arg_start = 1;
    /* Everything the shared cleanup label reads is declared and initialized
     * here, above the option loop, so any later error path can `goto cleanup`:
     * a goto that skipped an initializer would leave the unwind reading
     * indeterminate state. Zero state makes every cleanup step a no-op.
     */
    char *elf_path = NULL;
    char *sysroot_path = NULL;
    const char **guest_argv = NULL;
    int guest_argc = 0;
    sysroot_mount_t sysroot_mount;
    char host_cwd[LINUX_PATH_MAX];
    char elf_host_path[LINUX_PATH_MAX];
    bool elf_host_temp = false;
    bool have_host_cwd = (getcwd(host_cwd, sizeof(host_cwd)) != NULL);
    int exit_code = 1;
    memset(&sysroot_mount, 0, sizeof(sysroot_mount));

    /* 'elfuse rosettad translate <in> <out>' runs the real Apple rosettad
     * binary inside an elfuse guest to materialise an AOT translation. The
     * rosettad bridge in src/core/rosetta.c invokes this on cache miss; the
     * subcommand rewrites argv so the rest of main proceeds as a normal
     * aarch64-linux execution of rosettad with the requested arguments.
     */
    if (argc >= 5 && !strcmp(argv[1], "rosettad") &&
        !strcmp(argv[2], "translate")) {
        static char *rewritten[6];
        rewritten[0] = argv[0];
        rewritten[1] = (char *) ROSETTAD_TRANSLATOR_PATH;
        rewritten[2] = (char *) "translate";
        rewritten[3] = argv[3];
        rewritten[4] = argv[4];
        rewritten[5] = NULL;
        argv = rewritten;
        argc = 5;
    }

    /* --help and --version do not require an ELF path. */
    if (argc > 1) {
        if (!strcmp(argv[1], "--version") || !strcmp(argv[1], "-V")) {
            printf("elfuse %s\n", ELFUSE_VERSION);
            return 0;
        }
        if (!strcmp(argv[1], "--help") || !strcmp(argv[1], "-h")) {
            printf(
                ELFUSE_USAGE_WRAPPED
                "\n"
                "\n"
                "Options:\n"
                "  -h, --help              Show this help and exit\n"
                "  -V, --version           Show version and exit\n"
                "  -v, --verbose           Trace each guest syscall\n"
                "  --timeout N             Per-iteration vCPU run timeout "
                "(seconds, default 10; 0 disables)\n"
                "  --sysroot PATH          Resolve absolute guest paths under "
                "PATH first\n"
                "  --create-sysroot PATH   Provision and use a case-sensitive "
                "APFS sparsebundle mounted at PATH\n"
                "  --no-rosetta            Disable x86_64-via-Rosetta "
                "(architecture is auto-detected from the ELF header; "
                "on by default)\n"
                "  --fakeroot              Enable fakeroot mode (sets guest "
                "UID/GID to 0 and provides full caps)\n"
                "  --gdb PORT              Listen for GDB Remote Serial "
                "Protocol on PORT\n"
                "  --gdb-stop-on-entry     Halt before the first guest "
                "instruction\n"
                "  --user UID[:GID]        Run the guest as UID (and GID; "
                "defaults to UID). Numeric; elfuse-oci resolves symbolic "
                "names\n"
                "  --workdir DIR           Guest-absolute initial working "
                "directory (resolved under --sysroot)\n"
                "\n"
                "Environment:\n"
                "  ELFUSE_NO_ROSETTA=1     Same as --no-rosetta\n"
                "  ELFUSE_FAKEROOT=1       Same as --fakeroot\n"
                "  ELFUSE_FAKEROOT_EXEC    Absolute path of the one executable "
                "whose exec enters fakeroot mode, letting a guest start "
                "unprivileged and raise privilege later; matched by file "
                "identity, and never dropped afterwards, so that image and "
                "everything it execs or forks stay root (unset: no exec ever "
                "elevates)\n");
            return 0;
        }
    }

    if (host_dc_zva_assert() < 0)
        goto cleanup;

    /* Parse elfuse options until the first guest argv element. */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (!strcmp(argv[arg_start], "--verbose") ||
            !strcmp(argv[arg_start], "-v")) {
            verbose = true;
            log_set_level(LOG_DEBUG);
            arg_start++;
        } else if ((!strcmp(argv[arg_start], "--timeout") ||
                    !strcmp(argv[arg_start], "-t")) &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX, &timeout_sec) <
                0)
                timeout_sec = 10;
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--fork-child") &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX, &fork_child_fd) <
                0) {
                log_error("invalid fork child fd: %s", argv[arg_start + 1]);
                goto cleanup;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--vfork-notify-fd") &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX,
                              &vfork_notify_fd) < 0) {
                log_error("invalid vfork notify fd: %s", argv[arg_start + 1]);
                goto cleanup;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--sysroot") &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--create-sysroot") &&
                   arg_start + 1 < argc) {
            create_sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--no-rosetta")) {
            rosetta_enabled = false;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--fakeroot")) {
            fakeroot = true;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--gdb") && arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 1, 65535, &gdb_port) < 0) {
                log_error("invalid GDB port: %s", argv[arg_start + 1]);
                goto cleanup;
            }
            if (!verbose)
                log_set_level(LOG_INFO);
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--gdb-stop-on-entry")) {
            gdb_stop_on_entry = true;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--user") && arg_start + 1 < argc) {
            const char *spec = argv[arg_start + 1];
            char *end;
            errno = 0;
            unsigned long u = strtoul(spec, &end, 10);
            if (errno || end == spec || u > UINT32_MAX) {
                log_error("invalid --user UID: %s", spec);
                goto cleanup;
            }
            unsigned long gg = u;
            if (*end == ':') {
                errno = 0;
                char *end2;
                gg = strtoul(end + 1, &end2, 10);
                if (errno || end2 == end + 1 || *end2 != '\0' ||
                    gg > UINT32_MAX) {
                    log_error("invalid --user UID:GID: %s", spec);
                    goto cleanup;
                }
            } else if (*end != '\0') {
                log_error("invalid --user spec: %s", spec);
                goto cleanup;
            }
            uid = (uint32_t) u;
            gid = (uint32_t) gg;
            has_creds = true;
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--workdir") &&
                   arg_start + 1 < argc) {
            /* Reject relative paths up front: translation would resolve
             * them against the host cwd, silently starting the guest outside
             * the intended tree. strdup now because
             * runtime_set_process_title clobbers the original argv block.
             */
            if (argv[arg_start + 1][0] != '/') {
                log_error("--workdir requires a guest-absolute path, got %s",
                          argv[arg_start + 1]);
                goto cleanup;
            }
            free(workdir);
            workdir = strdup(argv[arg_start + 1]);
            if (!workdir) {
                log_error("out of memory");
                goto cleanup;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--")) {
            arg_start++;
            break;
        } else {
            log_error("unknown option: %s", argv[arg_start]);
            log_error(ELFUSE_USAGE);
            goto cleanup;
        }
    }

    if (sysroot && create_sysroot) {
        log_error(
            "use either --sysroot PATH or --create-sysroot PATH, not both");
        goto cleanup;
    }

    /* ELFUSE_NO_ROSETTA=1 mirrors --no-rosetta for environments where passing
     * flags is awkward (test harnesses, wrapper scripts). Unset or any other
     * value leaves the default on. Commit the result before the --fork-child
     * early-return so helper processes inherit the parent's opt-out semantics
     * exactly.
     */
    if (rosetta_enabled) {
        const char *no_rosetta_env = getenv("ELFUSE_NO_ROSETTA");
        if (no_rosetta_env && strcmp(no_rosetta_env, "1") == 0)
            rosetta_enabled = false;
    }
    proc_set_rosetta_enabled(rosetta_enabled);

    if (!fakeroot) {
        const char *fakeroot_env = getenv("ELFUSE_FAKEROOT");
        if (fakeroot_env && strcmp(fakeroot_env, "1") == 0)
            fakeroot = true;
    }
    proc_set_fakeroot_enabled(fakeroot);

    /* Opt-in sudo-style transition: name one executable whose exec enters
     * fakeroot, so a guest can start unprivileged and raise privilege later.
     * Nothing happens unless the embedder sets this.
     *
     * A malformed value is fatal, like every other rejected option in the loop
     * above. Starting anyway would leave a guest whose marked command silently
     * never elevates, and a privilege boundary that fails quietly is worse than
     * one that refuses to start. Arming only records the path; whether it names
     * an existing file is decided per exec, so a missing file is not an error
     * here.
     */
    const char *fakeroot_exec_env = getenv("ELFUSE_FAKEROOT_EXEC");
    if (fakeroot_exec_env && *fakeroot_exec_env &&
        !proc_set_fakeroot_exec_path(fakeroot_exec_env)) {
        log_error(
            "ELFUSE_FAKEROOT_EXEC must be an absolute path shorter than %d "
            "bytes",
            LINUX_PATH_MAX);
        goto cleanup;
    }

    /* Top-level processes establish the capacity; fork helpers normally inherit
     * it, but recheck before receiving the parent's FD table. Guest
     * RLIMIT_NOFILE state is virtualized separately and cannot lower this
     * internal host reserve.
     */
    if (host_nofile_ensure_capacity() < 0)
        goto cleanup;

    /* Block the vCPU-preemption signals and start the sigwait thread before any
     * vCPU thread exists, so both the normal path and the fork-child path below
     * inherit the block on every thread they spawn.
     */
    if (proc_preempt_init() < 0)
        goto cleanup;

    /* Fork-child mode: receive VM state over IPC and run */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, vfork_notify_fd, verbose,
                               timeout_sec);

    if (arg_start >= argc) {
        log_error(ELFUSE_USAGE);
        goto cleanup;
    }

    /* Copy elf_path and guest_argv to heap because the original argv string
     * data lives in a contiguous stack region that elfuse clobbers below for
     * the process title (PostgreSQL/nginx argv-clobber technique).
     */
    elf_path = strdup(argv[arg_start]);
    bool have_sysroot = (sysroot != NULL || create_sysroot != NULL);
    const char *sysroot_src = create_sysroot ? create_sysroot : sysroot;
    if (have_sysroot) {
        sysroot_path = (char *) calloc(LINUX_PATH_MAX, 1);
        if (sysroot_path) {
            size_t src_len =
                str_copy_trunc(sysroot_path, sysroot_src, LINUX_PATH_MAX);
            if (src_len >= LINUX_PATH_MAX) {
                log_error("sysroot path too long (%zu bytes, max %d): %s",
                          src_len, LINUX_PATH_MAX - 1, sysroot_src);
                goto cleanup;
            }
        }
    }
    sysroot = sysroot_path;
    guest_argc = argc - arg_start;
    guest_argv = (const char **) calloc((size_t) guest_argc, sizeof(char *));
    if (!elf_path || (have_sysroot && !sysroot_path) || !guest_argv) {
        log_error("out of memory");
        goto cleanup;
    }
    for (int i = 0; i < guest_argc; i++) {
        guest_argv[i] = strdup(argv[arg_start + i]);
        if (!guest_argv[i]) {
            log_error("out of memory");
            goto cleanup;
        }
    }

    if (create_sysroot) {
        if (sysroot_create_mount(sysroot_path, &sysroot_mount) < 0) {
            log_error("failed to provision case-sensitive sysroot at %s: %s",
                      sysroot_path, strerror(errno));
            goto cleanup;
        }
        size_t mounted_len = str_copy_trunc(
            sysroot_path, sysroot_mount.mount_path, LINUX_PATH_MAX);
        if (mounted_len >= LINUX_PATH_MAX) {
            log_error("mounted sysroot path too long: %s",
                      sysroot_mount.mount_path);
            goto cleanup;
        }
        sysroot = sysroot_path;
    }

    if (have_sysroot && sysroot_validate_case_sensitivity(sysroot) < 0)
        goto cleanup;

    proc_set_sysroot(sysroot);

    int shebang_depth = 0;

    while (true) {
        if (resolve_guest_elf_host_path(elf_path, elf_host_path,
                                        sizeof(elf_host_path),
                                        &elf_host_temp) < 0) {
            log_error("failed to resolve ELF path %s: %s", elf_path,
                      strerror(errno));
            goto cleanup;
        }

        /* Check if the file starts with "#!" */
        char interp[LINUX_PATH_MAX];
        char arg[LINUX_PATH_MAX];
        int rc = elf_read_shebang(elf_host_path, interp, sizeof(interp), arg,
                                  sizeof(arg));
        if (rc == 0) {
            /* Not a shebang script, proceed to boot */
            break;
        }

        if (rc < 0) {
            log_error("empty or invalid shebang interpreter in %s", elf_path);
            goto cleanup;
        }

        /* The current path is a script. Bound the resolution chain only once a
         * further shebang is confirmed, so a max-depth chain ending in a real
         * ELF still boots (matches sys_execve and the Linux kernel).
         */
        if (shebang_depth >= ELF_SHEBANG_MAX_DEPTH) {
            log_error(
                "too many levels of shebang recursion (max %d) "
                "resolving %s",
                ELF_SHEBANG_MAX_DEPTH, argv[arg_start]);
            goto cleanup;
        }
        shebang_depth++;

        /* Prepend interpreter (and argument if present) to guest_argv */
        bool has_arg = (arg[0] != '\0');
        int add_count = has_arg ? 2 : 1;
        int new_argc = guest_argc + add_count;
        const char **new_argv =
            (const char **) calloc((size_t) new_argc, sizeof(char *));
        if (!new_argv) {
            log_error("out of memory");
            goto cleanup;
        }

        new_argv[0] = strdup(interp);
        if (!new_argv[0]) {
            log_error("out of memory");
            free((void *) new_argv);
            goto cleanup;
        }
        if (has_arg) {
            new_argv[1] = strdup(arg);
            if (!new_argv[1]) {
                log_error("out of memory");
                free((void *) new_argv[0]);
                free((void *) new_argv);
                goto cleanup;
            }
        }

        /* Transfer ownership of the previous guest_argv elements */
        for (int i = 0; i < guest_argc; i++) {
            new_argv[i + add_count] = guest_argv[i];
        }

        free((void *) guest_argv);
        guest_argv = new_argv;
        guest_argc = new_argc;

        /* Update elf_path to point to the interpreter path */
        char *new_elf_path = strdup(interp);
        if (!new_elf_path) {
            log_error("out of memory");
            goto cleanup;
        }
        free(elf_path);
        elf_path = new_elf_path;

        /* Clean up any materialized temp file before resolving the next path */
        if (elf_host_temp) {
            unlink(elf_host_path);
            elf_host_temp = false;
        }
    }

    if (gdb_port > 0) {
        elf_info_t probe_info;
        if (guest_bootstrap_probe_elf(elf_host_path, &probe_info) == 0 &&
            probe_info.e_machine == EM_X86_64) {
            log_error(LAUNCH_GDB_X86_64_MSG);
            goto cleanup;
        }
    }

    /* Rewrite the host-visible process title from the guest entrypoint. This
     * clobbers the original argv block (already snapshotted into the heap
     * elf_path / guest_argv above), so it must run before elfuse_launch hands
     * control to the guest but after the shebang loop has fixed elf_path.
     */
    runtime_set_process_title(argc, argv, elf_path);

    /* Hand the bring-up, run loop, and guest teardown to elfuse_launch. main()
     * retains ownership of the original argv (proctitle above), the sysroot
     * mount (detached at the cleanup label after the guest exits so the
     * mount stays live for the whole run), host cwd, and the heap elf_path /
     * sysroot_path / guest_argv / workdir copies.
     */
    launch_args_t largs = {
        .elf_path = elf_host_path,
        .elf_host_temp = elf_host_temp,
        .sysroot = sysroot,
        .guest_argc = guest_argc,
        .guest_argv = guest_argv,
        .has_creds = has_creds,
        .uid = uid,
        .gid = gid,
        .cwd_guest = workdir,
        .gdb_port = gdb_port,
        .gdb_stop_on_entry = gdb_stop_on_entry,
        .timeout_sec = timeout_sec,
        .verbose = verbose,
    };
    /* Ownership of the temp unlink transfers here (contract in launch.h);
     * drop main()'s claim so the shared cleanup below cannot double-unlink.
     */
    elf_host_temp = false;
    exit_code = elfuse_launch(&largs);

cleanup:
    /* Single unwind for every exit past the state block above: frees the
     * caller-owned heap copies, detaches the sysroot mount, restores the host
     * cwd, and drops a still-owned FUSE-materialized temp ELF. This must run
     * even after a bring-up whose HVF teardown guest_destroy deferred to
     * process exit, because process exit reclaims neither the sysroot mount
     * nor the temp ELF. The guest itself belongs to elfuse_launch, which
     * destroys it on every exit path, so nothing here touches HVF or guest
     * memory.
     */
    rosettad_clear_binary_path();
    if (have_host_cwd && host_cwd[0] != '\0' && chdir(host_cwd) < 0)
        (void) chdir("/");
    sysroot_cleanup_mount(&sysroot_mount);
    free_guest_argv(guest_argv, guest_argc);
    free(elf_path);
    free(sysroot_path);
    free(workdir);
    if (elf_host_temp)
        unlink(elf_host_path);

    return exit_code;
}
