/*
 * Run aarch64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2026 elfuse contributors
 * Copyright 2025 Moritz Angermann, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MiB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *
 * Usage: elfuse [--verbose] [--timeout N] [--sysroot PATH] <elf-path> [args...]
 */

#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "utils.h"

#include "core/bootstrap.h"
#include "core/guest.h"
#include "core/rosetta.h"
#include "core/shim-globals.h"
#include "core/sysroot.h"

#include "oci/cli.h"

#include "runtime/forkipc.h"
#include "runtime/proctitle.h"

#include "syscall/fuse.h"
#include "syscall/path.h"
#include "syscall/proc.h"

#include "debug/gdbstub.h"
#include "debug/log.h"
#include "debug/syscall-hist.h"

static int parse_int_arg(const char *s, int min, int max, int *out)
{
    char *end = NULL;
    errno = 0;
    long value = strtol(s, &end, 10);
    if (errno != 0 || end == s || *end != '\0' || value < min || value > max)
        return -1;
    *out = (int) value;
    return 0;
}

static int resolve_guest_elf_host_path(const char *elf_guest_path,
                                       char *elf_host_path,
                                       size_t elf_host_path_sz,
                                       bool *elf_host_temp)
{
    path_translation_t tx;
    if (!elf_guest_path || !elf_host_path || elf_host_path_sz == 0 ||
        !elf_host_temp) {
        errno = EINVAL;
        return -1;
    }

    *elf_host_temp = false;
    if (path_translate_at(LINUX_AT_FDCWD, elf_guest_path, PATH_TR_NONE, &tx) <
        0)
        return -1;

    if (tx.fuse_path) {
        int rc = fuse_materialize_path(tx.intercept_path, elf_host_path,
                                       elf_host_path_sz);
        if (rc < 0) {
            errno = -rc;
            return -1;
        }
        *elf_host_temp = true;
        return 0;
    }

    size_t len = str_copy_trunc(elf_host_path, tx.host_path, elf_host_path_sz);
    if (len >= elf_host_path_sz) {
        errno = ENAMETOOLONG;
        return -1;
    }
    return 0;
}

static void free_guest_argv(const char **guest_argv, int guest_argc)
{
    if (!guest_argv)
        return;
    for (int i = 0; i < guest_argc; i++)
        free((void *) guest_argv[i]);
    free((void *) guest_argv);
}

static void cleanup_main_resources(guest_t *g,
                                   bool guest_initialized,
                                   sysroot_mount_t *sysroot_mount,
                                   const char *host_cwd,
                                   const char **guest_argv,
                                   int guest_argc,
                                   char *elf_path,
                                   char *sysroot_path)
{
    if (guest_initialized)
        guest_destroy(g);
    rosettad_clear_binary_path();
    if (host_cwd && host_cwd[0] != '\0' && chdir(host_cwd) < 0)
        (void) chdir("/");
    sysroot_cleanup_mount(sysroot_mount);
    free_guest_argv(guest_argv, guest_argc);
    free((void *) elf_path);
    free((void *) sysroot_path);
}

/* Embedded shim binary (generated by xxd -i from shim.bin) */
#include "shim_blob.h"

/* The shim code slot in the infra reserve is sized tight (INFRA_SHIM_SLOT, a
 * few x the current blob) so the rest of the reserve goes to the page-table
 * pool. If the shim ever outgrows the slot it would overlap the shim-data
 * block; fail the build loudly rather than corrupt memory at boot. Enlarge
 * INFRA_SHIM_SLOT (and shrink the pool to match) if this fires.
 */
_Static_assert(sizeof(shim_bin) <= INFRA_SHIM_SLOT,
               "shim blob exceeds its infra slot; bump INFRA_SHIM_SLOT");

/* The infra-reserve layout invariants documented in guest.h are derived from
 * raw offset constants, so a future edit that grows the pool by shifting one
 * offset without the others would silently overlap two regions. Enforce them at
 * build time rather than trusting the comment.
 */
_Static_assert(INFRA_PT_POOL_END_OFF == INFRA_SHIM_OFF,
               "PT pool must end exactly where the shim slot begins");
_Static_assert(INFRA_SHIM_DATA_OFF + BLOCK_2MIB == INFRA_RESERVE,
               "shim_data must occupy the top 2MiB block of the reserve");
_Static_assert((INFRA_SHIM_DATA_OFF & (BLOCK_2MIB - 1)) == 0,
               "shim_data must be 2MiB-aligned");
_Static_assert((INFRA_PT_POOL_OFF & 0xFFF) == 0 &&
                   (INFRA_PT_POOL_END_OFF & 0xFFF) == 0,
               "PT pool offsets must be page-aligned");

/* Build-time version string (generated by make into build/version.h) */
#include "version.h"

/* Verify the host CPU's DC ZVA granule matches the shim's hardcoded value.
 *
 * DCZID_EL0 is readable from EL0 without trapping, so guest libc reads the
 * host's value directly and uses it as the stride for memset(0) loops. The shim
 * emulates each trapped DC ZVA by zeroing exactly 64 bytes (src/core/shim.S).
 * Apple Silicon M1..M4 report DCZID_EL0.BS=4 (64 bytes); any future host that
 * advertises a different granule would cause silent partial-zero corruption of
 * guest memory. Abort here so the mismatch surfaces at startup instead of as
 * data corruption later.
 */
static int host_dc_zva_assert(void)
{
    uint64_t dczid;
    __asm__ volatile("mrs %0, DCZID_EL0" : "=r"(dczid));
    if (dczid & (1ULL << 4)) {
        log_error(
            "host CPU prohibits DC ZVA (DCZID_EL0.DZP=1); cannot run "
            "guests that depend on it");
        return -1;
    }
    unsigned bs = (unsigned) (dczid & 0xF);
    if (bs != 4) {
        log_error(
            "host DCZID_EL0.BS=%u (%u-byte DC ZVA block) but the shim "
            "emulates 64 bytes; update src/core/shim.S before running",
            bs, 1u << (bs + 2));
        return -1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    log_init();
    /* Resolve ELFUSE_STARTUP_TRACE before any guest syscall can fire so the
     * histogram captures the very first dynamic-linker openat.
     */
    syscall_hist_init();

    bool verbose = false;
    /* x86_64-via-Rosetta is on by default; --no-rosetta or ELFUSE_NO_ROSETTA=1
     * disables it. Architecture is auto-detected from the ELF header in
     * guest_bootstrap_prepare; the access() probe in rosetta_prepare surfaces
     * an install hint if Rosetta is not present.
     */
    bool rosetta_enabled = true;
    int timeout_sec = 10, fork_child_fd = -1, vfork_notify_fd = -1;
    const char *sysroot = NULL;
    const char *create_sysroot = NULL;
    int gdb_port = 0;
    bool gdb_stop_on_entry = false;
    bool fakeroot = false;
    int arg_start = 1;

    /* 'elfuse rosettad translate <in> <out>' runs the real Apple rosettad
     * binary inside an elfuse guest to materialise an AOT translation. The
     * rosettad bridge in src/core/rosetta.c invokes this on cache miss; the
     * subcommand rewrites argv so the rest of main proceeds as a normal
     * aarch64-linux execution of rosettad with the requested arguments.
     */
    if (argc >= 5 && !strcmp(argv[1], "rosettad") &&
        !strcmp(argv[2], "translate")) {
        static char *rewritten[6];
        rewritten[0] = argv[0];
        rewritten[1] = (char *) ROSETTAD_TRANSLATOR_PATH;
        rewritten[2] = (char *) "translate";
        rewritten[3] = argv[3];
        rewritten[4] = argv[4];
        rewritten[5] = NULL;
        argv = rewritten;
        argc = 5;
    }

    /* BusyBox-style multicall dispatch: invoked through a symlink named
     * elfuse-container (ln -s elfuse elfuse-container), the whole command
     * line is the container CLI — `elfuse-container run alpine:3` is
     * `elfuse oci run alpine:3`. One binary, two spellings; oci_cli_main
     * brands usage text with the alias it sees in argv[0]. Only the
     * basename participates in the lookup, so an invocation name cannot
     * smuggle a directory component into applet selection, and an
     * unrecognized name falls through to the default elfuse behavior
     * (closed applet table, matching BusyBox). An execve with an empty
     * argv leaves argv[0] NULL; treat that as the default entry.
     */
    const char *invoked_as = "elfuse";
    if (argc > 0 && argv[0]) {
        const char *argv0_slash = strrchr(argv[0], '/');
        invoked_as = argv0_slash ? argv0_slash + 1 : argv[0];
    }
    if (!strcmp(invoked_as, "elfuse-container"))
        return oci_cli_main(argc, argv);

    /* `elfuse oci ...` is a self-contained CLI subcommand: image distribution
     * never touches Hypervisor.framework, so dispatch before any guest setup
     * to avoid host-DC-ZVA / entitlement checks the user never asked for.
     */
    if (argc > 1 && !strcmp(argv[1], "oci"))
        return oci_cli_main(argc - 1, argv + 1);

    /* --help and --version do not require an ELF path. */
    if (argc > 1) {
        if (!strcmp(argv[1], "--version") || !strcmp(argv[1], "-V")) {
            printf("elfuse %s\n", ELFUSE_VERSION);
            return 0;
        }
        if (!strcmp(argv[1], "--help") || !strcmp(argv[1], "-h")) {
            printf(
                "usage: elfuse [--verbose] [--timeout N] [--sysroot PATH]\n"
                "              [--create-sysroot PATH]\n"
                "              [--no-rosetta] [--fakeroot]\n"
                "              [--gdb PORT] [--gdb-stop-on-entry]\n"
                "              <elf-path> [args...]\n"
                "\n"
                "Options:\n"
                "  -h, --help              Show this help and exit\n"
                "  -V, --version           Show version and exit\n"
                "  -v, --verbose           Trace each guest syscall\n"
                "  --timeout N             Per-iteration vCPU run timeout "
                "(seconds, default 10; 0 disables)\n"
                "  --sysroot PATH          Resolve absolute guest paths under "
                "PATH first\n"
                "  --create-sysroot PATH   Provision and use a case-sensitive "
                "APFS sparsebundle mounted at PATH\n"
                "  --no-rosetta            Disable x86_64-via-Rosetta "
                "(architecture is auto-detected from the ELF header; "
                "on by default)\n"
                "  --fakeroot              Enable fakeroot mode (sets guest "
                "UID/GID to 0 and provides full caps)\n"
                "  --gdb PORT              Listen for GDB Remote Serial "
                "Protocol on PORT\n"
                "  --gdb-stop-on-entry     Halt before the first guest "
                "instruction\n");
            return 0;
        }
    }

    if (host_dc_zva_assert() < 0)
        return 1;

    /* Parse elfuse options until the first guest argv element. */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (!strcmp(argv[arg_start], "--verbose") ||
            !strcmp(argv[arg_start], "-v")) {
            verbose = true;
            log_set_level(LOG_DEBUG);
            arg_start++;
        } else if ((!strcmp(argv[arg_start], "--timeout") ||
                    !strcmp(argv[arg_start], "-t")) &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX, &timeout_sec) <
                0)
                timeout_sec = 10;
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--fork-child") &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX, &fork_child_fd) <
                0) {
                log_error("invalid fork child fd: %s", argv[arg_start + 1]);
                return 1;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--vfork-notify-fd") &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX,
                              &vfork_notify_fd) < 0) {
                log_error("invalid vfork notify fd: %s", argv[arg_start + 1]);
                return 1;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--sysroot") &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--create-sysroot") &&
                   arg_start + 1 < argc) {
            create_sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--no-rosetta")) {
            rosetta_enabled = false;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--fakeroot")) {
            fakeroot = true;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--gdb") && arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 1, 65535, &gdb_port) < 0) {
                log_error("invalid GDB port: %s", argv[arg_start + 1]);
                return 1;
            }
            if (!verbose)
                log_set_level(LOG_INFO);
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--gdb-stop-on-entry")) {
            gdb_stop_on_entry = true;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--")) {
            arg_start++;
            break;
        } else {
            log_error("unknown option: %s", argv[arg_start]);
            log_error(
                "usage: elfuse [--verbose] [--timeout N] "
                "[--sysroot PATH] [--create-sysroot PATH] [--no-rosetta] "
                "[--fakeroot] [--gdb PORT] "
                "[--gdb-stop-on-entry] <elf-path> [args...]");
            return 1;
        }
    }

    if (sysroot && create_sysroot) {
        log_error(
            "use either --sysroot PATH or --create-sysroot PATH, not both");
        return 1;
    }

    /* ELFUSE_NO_ROSETTA=1 mirrors --no-rosetta for environments where passing
     * flags is awkward (test harnesses, wrapper scripts). Unset or any other
     * value leaves the default on. Commit the result before the --fork-child
     * early-return so helper processes inherit the parent's opt-out semantics
     * exactly.
     */
    if (rosetta_enabled) {
        const char *no_rosetta_env = getenv("ELFUSE_NO_ROSETTA");
        if (no_rosetta_env && strcmp(no_rosetta_env, "1") == 0)
            rosetta_enabled = false;
    }
    proc_set_rosetta_enabled(rosetta_enabled);

    if (!fakeroot) {
        const char *fakeroot_env = getenv("ELFUSE_FAKEROOT");
        if (fakeroot_env && strcmp(fakeroot_env, "1") == 0)
            fakeroot = true;
    }
    proc_set_fakeroot_enabled(fakeroot);

    /* Fork-child mode: receive VM state over IPC and run */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, vfork_notify_fd, verbose,
                               timeout_sec);

    if (arg_start >= argc) {
        log_error(
            "usage: elfuse [--verbose] [--timeout N] "
            "[--sysroot PATH] [--create-sysroot PATH] [--no-rosetta] "
            "[--fakeroot] <elf-path> [args...]");
        return 1;
    }

    /* Copy elf_path and guest_argv to heap because the original argv string
     * data lives in a contiguous stack region that elfuse clobbers below for
     * the process title (PostgreSQL/nginx argv-clobber technique).
     */
    char *elf_path = strdup(argv[arg_start]);
    bool have_sysroot = (sysroot != NULL || create_sysroot != NULL);
    const char *sysroot_src = create_sysroot ? create_sysroot : sysroot;
    char *sysroot_path = NULL;
    if (have_sysroot) {
        sysroot_path = (char *) calloc(LINUX_PATH_MAX, 1);
        if (sysroot_path) {
            size_t src_len =
                str_copy_trunc(sysroot_path, sysroot_src, LINUX_PATH_MAX);
            if (src_len >= LINUX_PATH_MAX) {
                log_error("sysroot path too long (%zu bytes, max %d): %s",
                          src_len, LINUX_PATH_MAX - 1, sysroot_src);
                free(elf_path);
                free(sysroot_path);
                return 1;
            }
        }
    }
    sysroot = sysroot_path;
    int guest_argc = argc - arg_start;
    const char **guest_argv =
        (const char **) calloc((size_t) guest_argc, sizeof(char *));
    guest_t g;
    bool guest_initialized = false;
    sysroot_mount_t sysroot_mount;
    char host_cwd[LINUX_PATH_MAX];
    char elf_host_path[LINUX_PATH_MAX];
    bool elf_host_temp = false;
    bool have_host_cwd = (getcwd(host_cwd, sizeof(host_cwd)) != NULL);
    memset(&sysroot_mount, 0, sizeof(sysroot_mount));
    if (!elf_path || (have_sysroot && !sysroot_path) || !guest_argv) {
        log_error("out of memory");
        cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                               have_host_cwd ? host_cwd : NULL, guest_argv,
                               guest_argc, elf_path, sysroot_path);
        return 1;
    }
    for (int i = 0; i < guest_argc; i++) {
        guest_argv[i] = strdup(argv[arg_start + i]);
        if (!guest_argv[i]) {
            log_error("out of memory");
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            return 1;
        }
    }

    if (create_sysroot) {
        if (sysroot_create_mount(sysroot_path, &sysroot_mount) < 0) {
            log_error("failed to provision case-sensitive sysroot at %s: %s",
                      sysroot_path, strerror(errno));
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            return 1;
        }
        size_t mounted_len = str_copy_trunc(
            sysroot_path, sysroot_mount.mount_path, LINUX_PATH_MAX);
        if (mounted_len >= LINUX_PATH_MAX) {
            log_error("mounted sysroot path too long: %s",
                      sysroot_mount.mount_path);
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            return 1;
        }
        sysroot = sysroot_path;
    }

    if (have_sysroot && sysroot_validate_case_sensitivity(sysroot) < 0) {
        cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                               have_host_cwd ? host_cwd : NULL, guest_argv,
                               guest_argc, elf_path, sysroot_path);
        return 1;
    }

    proc_set_sysroot(sysroot);

    int shebang_depth = 0;
    const int max_shebang_depth = 5;

    while (shebang_depth < max_shebang_depth) {
        if (resolve_guest_elf_host_path(elf_path, elf_host_path,
                                        sizeof(elf_host_path),
                                        &elf_host_temp) < 0) {
            log_error("failed to resolve ELF path %s: %s", elf_path,
                      strerror(errno));
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            if (elf_host_temp)
                unlink(elf_host_path);
            return 1;
        }

        /* Check if the file starts with "#!" */
        char interp[LINUX_PATH_MAX];
        char arg[LINUX_PATH_MAX];
        int rc = elf_read_shebang(elf_host_path, interp, sizeof(interp), arg,
                                  sizeof(arg));
        if (rc == 0) {
            /* Not a shebang script, proceed to boot */
            break;
        }

        if (rc < 0) {
            log_error("empty or invalid shebang interpreter in %s", elf_path);
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            if (elf_host_temp)
                unlink(elf_host_path);
            return 1;
        }

        shebang_depth++;

        /* Prepend interpreter (and argument if present) to guest_argv */
        bool has_arg = (arg[0] != '\0');
        int add_count = has_arg ? 2 : 1;
        int new_argc = guest_argc + add_count;
        const char **new_argv =
            (const char **) calloc((size_t) new_argc, sizeof(char *));
        if (!new_argv) {
            log_error("out of memory");
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            if (elf_host_temp)
                unlink(elf_host_path);
            return 1;
        }

        new_argv[0] = strdup(interp);
        if (!new_argv[0]) {
            log_error("out of memory");
            free((void *) new_argv);
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            if (elf_host_temp)
                unlink(elf_host_path);
            return 1;
        }
        if (has_arg) {
            new_argv[1] = strdup(arg);
            if (!new_argv[1]) {
                log_error("out of memory");
                free((void *) new_argv[0]);
                free((void *) new_argv);
                cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                       have_host_cwd ? host_cwd : NULL,
                                       guest_argv, guest_argc, elf_path,
                                       sysroot_path);
                if (elf_host_temp)
                    unlink(elf_host_path);
                return 1;
            }
        }

        /* Transfer ownership of the previous guest_argv elements */
        for (int i = 0; i < guest_argc; i++) {
            new_argv[i + add_count] = guest_argv[i];
        }

        free((void *) guest_argv);
        guest_argv = new_argv;
        guest_argc = new_argc;

        /* Update elf_path to point to the interpreter path */
        char *new_elf_path = strdup(interp);
        if (!new_elf_path) {
            log_error("out of memory");
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            if (elf_host_temp)
                unlink(elf_host_path);
            return 1;
        }
        free(elf_path);
        elf_path = new_elf_path;

        /* Clean up any materialized temp file before resolving the next path */
        if (elf_host_temp) {
            unlink(elf_host_path);
            elf_host_temp = false;
        }
    }

    if (shebang_depth >= max_shebang_depth) {
        log_error("too many levels of shebang recursion (max %d) resolving %s",
                  max_shebang_depth, argv[arg_start]);
        cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                               have_host_cwd ? host_cwd : NULL, guest_argv,
                               guest_argc, elf_path, sysroot_path);
        return 1;
    }

    if (gdb_port > 0) {
        elf_info_t probe_info;
        if (guest_bootstrap_probe_elf(elf_host_path, &probe_info) == 0 &&
            probe_info.e_machine == EM_X86_64) {
            log_error(
                "--gdb is not supported for x86_64 guests; the current stub "
                "only exposes the translated aarch64 view");
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            if (elf_host_temp)
                unlink(elf_host_path);
            return 1;
        }
    }

    guest_bootstrap_t boot;
    extern char **environ;

    if (guest_bootstrap_prepare(&g, elf_host_path, elf_host_temp, elf_path,
                                sysroot, guest_argc, guest_argv, environ,
                                shim_bin, shim_bin_len, verbose,
                                &guest_initialized, &boot) < 0) {
        cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                               have_host_cwd ? host_cwd : NULL, guest_argv,
                               guest_argc, elf_path, sysroot_path);
        if (elf_host_temp)
            unlink(elf_host_path);
        return 1;
    }
    if (elf_host_temp && !g.is_rosetta) {
        unlink(elf_host_path);
        elf_host_temp = false;
    }

    if (have_sysroot) {
        bool case_sensitive = true;
        bool case_preserving = true;
        if (sysroot_probe_case_sensitivity(sysroot, &case_sensitive,
                                           &case_preserving) == 0) {
            proc_set_sysroot_casefold(case_preserving && !case_sensitive);
        } else {
            proc_set_sysroot_casefold(false);
        }
    } else {
        proc_set_sysroot_casefold(false);
    }

    runtime_set_process_title(argc, argv, elf_path);

    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    if (guest_bootstrap_create_vcpu(&g, &boot, verbose, &vcpu, &vexit) < 0) {
        cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                               have_host_cwd ? host_cwd : NULL, guest_argv,
                               guest_argc, elf_path, sysroot_path);
        return 1;
    }

    /* GDB setup must happen before the first run so entry-stop and hardware
     * breakpoints can affect the initial vCPU.
     */
    if (gdb_port > 0) {
        if (gdb_stub_init(gdb_port, &g) < 0) {
            log_error("failed to initialize GDB stub");
            cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                                   have_host_cwd ? host_cwd : NULL, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            return 1;
        }
        /* Mirror any preconfigured breakpoints/watchpoints into this vCPU. */
        gdb_stub_sync_debug_regs(vcpu);

        if (gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    }

    /* vcpu_run_loop owns guest execution until exit, fatal signal, or timeout.
     */
    int exit_code = vcpu_run_loop(vcpu, vexit, &g, verbose, timeout_sec);

    /* Tear down debugger state before freeing guest/vCPU resources. */
    gdb_stub_shutdown();

    /* Diagnostic counter dump runs before guest_destroy so the shim_data
     * mapping is still valid. ELFUSE_SHIM_STATS is the gate; an unset variable
     * produces no output.
     */
    if (shim_globals_stats_enabled())
        shim_globals_counters_dump(&g);

    /* Dump the startup histogram before guest_destroy so any cleanup-path
     * syscalls (closing host fds, unmapping the slab) do not appear in the
     * captured set. The dump is a no-op when ELFUSE_STARTUP_TRACE=syscalls was
     * not requested.
     */
    syscall_hist_dump();
    cleanup_main_resources(&g, guest_initialized, &sysroot_mount,
                           have_host_cwd ? host_cwd : NULL, guest_argv,
                           guest_argc, elf_path, sysroot_path);

    return exit_code;
}
